#!/usr/bin/env python
import datetime
import xmlrpclib
import csv
from python_helper import *

username = "admin"
pwd = "1"
dbname = "test_sync"
server = "http://erp.nt999.net:8069"

sock_common = xmlrpclib.ServerProxy("%s/xmlrpc/common"%server)

uid = sock_common.login(dbname, username, pwd)

sock = xmlrpclib.ServerProxy("%s/xmlrpc/object"%server)

today_str = datetime.date.today().strftime("%Y-%m-%d")
imp_arrays = [['product.uom',"export/product_uom_%s.csv"%today_str],
    ['product.category',"export/product_category_%s.csv"%today_str],
    ['product.product',"export/product_product_%s.csv"%today_str],
    ['stock.inventory',"export/stock_inventory_%s.csv"%today_str],
    ['stock.inventory.line',"export/stock_inventory_line_%s.csv"%today_str],]

for imp_data in imp_arrays:
  do_import(sock,dbname,uid,pwd,imp_data[0],imp_data[1])

#from external_id get internal id
external_inv_id = "ktv_stock_inventory_" + datetime.date.today().strftime("%Y-%m-%d")
inv_id = get_internal_id(sock,dbname,uid,pwd,external_inv_id)
print "inventory_id: %s" % inv_id

#action_confirm
res = sock.execute(dbname, uid, pwd, "stock.inventory","action_confirm", [inv_id])
print "button_confirm result : %s"%res
#action_done
res = sock.execute(dbname, uid, pwd, "stock.inventory", "action_done", [inv_id])
print "button_done result : %s"%res
