#!/usr/bin/env python

import datetime
import xmlrpclib
import csv
from python_helper import *

username = "admin"
pwd = "1"
dbname = "test_sync"
server = "http://erp.nt999.net:8069"

sock_common = xmlrpclib.ServerProxy("%s/xmlrpc/common"%server)

uid = sock_common.login(dbname, username, pwd)

sock = xmlrpclib.ServerProxy("%s/xmlrpc/object"%server)

do_import(sock,dbname,uid,pwd,"stock.inventory","seed/stock_inventory_reset_erp_sync.csv")

ids = sock.execute(dbname,uid,pwd,"stock.inventory","search",[("name","ilike","ktv_stock_inventory_reset_sync_flag")])

if ids:
    #action_confirm
    res = sock.execute(dbname, uid, pwd, "stock.inventory","action_confirm", ids)
    print "button_confirm result : %s"%res
    #action_done
    res = sock.execute(dbname, uid, pwd, "stock.inventory", "action_done", ids)
    print "button_done result : %s"%res
